#!/usr/bin/env python
from __future__ import print_function

import os
from subprocess import check_call
import sys

from sr.tools import spending, Config
from sr.tools.environment import get_config_filename
from sr.tools.spending import NotSpendingRepo


# Invoke ledger on the SR spending repo
# Check that we are indeed invoking it on spending.git
config = Config()

# Default to using the spending.git specified in the config
root = config["spending"]
if root is not None:
    root = os.path.expanduser(root)
else:
    # Not specified in the config
    root = os.getcwd()

try:
    # Check that it's actually spending.git
    root = spending.find_root( path = root )
except NotSpendingRepo:
    print("This isn't SR spending.git", file=sys.stderr)
    print("Solve this by either:", file=sys.stderr)
    print(" - Changing working directory to spending.git", file=sys.stderr)
    print(" - Set the 'spending' config option in {}".format(get_config_filename()), file=sys.stderr)
    sys.exit(1)

args = sys.argv

if "--file" not in sys.argv:
    # Tell ledger where to look
    args = [args[0]] + \
           [ "--file",
             os.path.join( root, "spending.dat" ) ] + \
           args[1:]

os.execvp( "ledger", args )
