#!/bin/bash -e

TAG=$(git describe --tags --exact-match)
VERSION=$(python setup.py --version)

test "$TAG" == "v$VERSION"

echo "Building $TAG"

./script/release/build.sh

echo "Uploading $TAG"

twine upload dist/*
