#!/usr/bin/env python
# Displays the serial number of connected mmc cards
from __future__ import print_function

import pyudev


con = pyudev.Context()

for dev in con.list_devices(subsystem="mmc"):
    print(dev.attributes["serial"])
