#!/usr/bin/env python
import argparse
import os, sys, subprocess
from sr import Config

parser = argparse.ArgumentParser( description = "Clone an SR git repository" )
parser.add_argument( "repo",
                     help = "Repository path -- e.g. tools.git" )
parser.add_argument( "dir", nargs="?",
                     help = "Directory to clone to (optional)" )
parser.add_argument( "-a", "--anonymous",
                     action = "store_true", default = False,
                     help = "Clone anonymously over git://" )
args = parser.parse_args()

config = Config()

if args.anonymous:
    prefix = "git://{0}/".format( config["server"] )
else:
    prefix = "{0}:".format( config["gerrit_ssh"] )

repo = args.repo
if repo[:len(prefix)] != prefix:
    repo = "{0}{1}".format( prefix, repo )

cmd = ["git", "clone", "--recursive", repo]
if args.dir != None:
    args += [args.dir]

subprocess.check_call( cmd )

clonedir = args.dir
if clonedir is None:
    clonedir = os.path.basename( args.repo )

    if clonedir[-4:] == ".git":
        clonedir = clonedir[:-4]

if not args.anonymous:
    # Set up the gerrit Change-Id commit hook

    subprocess.check_call(
        [ "scp",
          "{0}:hooks/commit-msg".format( config["gerrit_ssh"] ),
          os.path.join( clonedir, ".git", "hooks" ) ] )
