#!/usr/bin/env python
import argparse
import os, sys, subprocess

parser = argparse.ArgumentParser( description = "Clone an SR git repository" )
parser.add_argument( "repo",
                     help = "Repository path -- e.g. tools.git" )
parser.add_argument( "dir", nargs="?",
                     help = "Directory to clone to (optional)" )
parser.add_argument( "-a", "--anonymous",
                     action = "store_true", default = False,
                     help = "Clone anonymously over git://" )
args = parser.parse_args()

if args.anonymous:
    prefix = "git://srobo.org/"
else:
    prefix = "sr-gerrit:"

repo = args.repo
if repo[:len(prefix)] != prefix:
    repo = "{0}{1}".format( prefix, repo )

cmd = ["git", "clone", "--recursive", repo]
if args.dir != None:
    args += [args.dir]

subprocess.check_call( cmd )
