#!/usr/bin/env python
import urllib, sys, re

if len(sys.argv) > 2 or (len(sys.argv) == 2 and sys.argv[1] == "--help"):
    print "Usage: repolist [REGEX]"
    exit()

matcher = None
if len(sys.argv) == 2:
    matcher = re.compile( sys.argv[1] )

u = urllib.urlopen("https://www.studentrobotics.org/git/repolist")

for l in u.readlines():
    cpos = l.find(":")
    path = l[:cpos].strip()
    desc = l[cpos+1:].strip()

    if matcher == None or matcher.search(path):
        print path
