#!/usr/bin/env python

import json
import urllib, sys, re

if len(sys.argv) > 2 or (len(sys.argv) == 2 and sys.argv[1] == "--help"):
    print "Usage: repolist [REGEX]"
    exit()

matcher = None
if len(sys.argv) == 2:
    matcher = re.compile( sys.argv[1] )

u = urllib.urlopen("https://www.studentrobotics.org/gerrit/projects/?d")

raw_json = u.read()

NO_EXEC_PREFIX = ")]}'"
if raw_json.startswith(NO_EXEC_PREFIX):
    raw_json = raw_json[len(NO_EXEC_PREFIX):].strip()

projects_map = json.loads(raw_json)

for path, info in projects_map.items():
    path += '.git'
    if matcher == None or matcher.search(path):
        print path
