#!/usr/bin/env python
import sys, os
from inventory import *
import assetcode

if len(sys.argv) < 2:
    print "Usage: %s ASSET" % os.path.basename(sys.argv[0])
    print "Create a new instance of an asset with a unique asset code."
    print "ASSET is the name of an asset file in /.meta/parts"
    sys.exit(1)

assetname = sys.argv[1]

# Check we're being run in the inventory repo
gitdir = gettoplevel()
if not gitdir:
    print "This command must be run in the inventory git repository."
    sys.exit(2)

# Check that a template for the new asset exists
templatefn = os.path.join(gitdir, ".meta", "parts", assetname)
if not os.path.isfile(templatefn):
    print "A template for the asset \"%s\" could not be found. The default template will be used." % assetname
    templatefn = os.path.join(gitdir, ".meta", "parts", "default")

# Get the git name/email of the user
username = getusername()

userno = getusernumber(gitdir, username)
partno = getpartnumber(gitdir, userno)

assetcd = assetcode.num_to_code(userno, partno)
assetfn = "%s-sr%s" % (assetname, assetcd)

print "Created new asset with name \"%s\"" % assetfn

# Copy the template to the actual asset file
# Insert the asset code into the file while we're at it
templatefile = open(templatefn)
assetfile = open(assetfn, "w")

for line in templatefile:
    assetfile.write(line.replace("[ASSET_CODE]", assetcd))

templatefile.close()
assetfile.close()
