#!/usr/bin/env python
import sys, os
from inventory import *
import assetcode

if len(sys.argv) < 2:
    print "Usage: %s DIR" % os.path.basename(sys.argv[0])
    print "Where DIR is a directory to promote to a tracked assembly."
    print "If DIR does not exist it will be created"
    sys.exit(1)

dirname = sys.argv[1]

# Check we're being run in the inventory repo
gitdir = gettoplevel()
if not gitdir:
    print "This command must be run in the inventory git repository."
    sys.exit(2)

username = getusername()
userno = getusernumber(gitdir, username)
partno = getpartnumber(gitdir, userno)

assetcd = assetcode.num_to_code(userno, partno)

groupname = "%s-sr%s" % (dirname, assetcd)

if os.path.isdir(dirname):
    os.rename(dirname, groupname)
else:
    os.mkdir(groupname)

# TODO: Add 'info' file
