#!/usr/bin/env python
import sys, os
from inventory import *
import assetcode

if len(sys.argv) < 2:
    print "Usage: %s DIR" % os.path.basename(sys.argv[0])
    print "Where DIR is a directory to promote to a tracked assembly."
    print "If DIR does not exist it will be created"
    sys.exit(1)

dirname = sys.argv[1]

# Check we're being run in the inventory repo
gitdir = gettoplevel()
if not gitdir:
    print "This command must be run in the inventory git repository."
    sys.exit(2)

# Find out if there's a template for the 'info' file
templatefn = os.path.join(gitdir, ".meta", "assemblies", dirname)
if not os.path.isfile(templatefn):
    templatefn = os.path.join(gitdir, ".meta", "assemblies", "default")

username = getusername()
userno = getusernumber(gitdir, username)
partno = getpartnumber(gitdir, userno)

assetcd = assetcode.num_to_code(userno, partno)

groupname = "%s-sr%s" % (dirname, assetcd)

if os.path.isdir(dirname):
    os.rename(dirname, groupname)
else:
    os.mkdir(groupname)

# Copy the group template to the group dir
# Insert the asset code into the file while we're at it
templatefile = open(templatefn)
assetfile = open(os.path.join(groupname, "info"), "w")

for line in templatefile:
    assetfile.write(line.replace("[ASSET_CODE]", assetcd))

templatefile.close()
assetfile.close()
