#!/usr/bin/env python
import sys, os, re

if len(sys.argv) < 2:
    print "Usage: %s ASSET" % os.path.basename(sys.argv[0])
    print "Increment the 'revision' field of an asset/assembly"
    exit(1)

assetname = sys.argv[1]

if os.path.isdir(assetname):
    assetname = os.path.join(assetname, "info")
    if not os.path.isfile(assetname):
        print "Cannot find 'info' file for assembly"
        sys.exit(1)

os.rename(assetname, "%s-tmp" % assetname)

try:
    new = open(assetname, "w")
    old = open("%s-tmp" % assetname)

    for line in old:
        revmatch = re.match("^[ ]*revision\\s*:\\s*([0-9]+)", line)
        if revmatch:
            rev = int(revmatch.group(1))
            line = re.sub("([^0-9]*)[0-9]*([^0-9]*)", "\\g<1>%i\\g<2>" % (rev+1), line)
            
        new.write(line)
except:
    print "Failed to update revision number:", sys.exc_info()[0]
    os.rename("%s-tmp" % assetname, assetname)

else:
    os.remove("%s-tmp" % assetname)
    old.close()
    new.close()
