#!/usr/bin/env python
import sr.inventory as srinv
import sr.inventory.assetcode as assetcode
import sr.inventory.oldinv as oldinv
import sys, os, argparse

desc = "Find the location of a specific item in the inventory."

aparser = argparse.ArgumentParser(description=desc)
aparser.add_argument("partcodes", metavar="PART_CODE", nargs="+", help="The SR asset code of the item to find.")

args = aparser.parse_args()

top = oldinv.gettoplevel()
if top == None:
    print >>sys.stderr, "Error: Must be run from within the inventory."
    exit(1)
inv = srinv.Inventory(top)

parts = []
for c in args.partcodes:
    code = c.upper().strip()
    if code[0:2] == "SR":
        code = code[2:]

    try:
        assetcode.code_to_num(code)
    except:
        print >>sys.stderr, "Error: %s is an invalid code." % code
        exit(1)

    try:
        part = inv.root.parts[code]
    except KeyError:
        print >>sys.stderr, "Error: There is no part with code %s." % code
        exit(1)

    parts.append(part)

for part in parts:
    print part.path
