#!/usr/bin/env python
from __future__ import print_function

import json
try:
    from urllib2 import urlopen
except ImportError:
    from urllib.request import urlopen


url = 'https://www.studentrobotics.org/ide/control.php/info/about'


if __name__ == '__main__':
    page = urlopen(url).read()
    data = json.loads(page.decode('utf-8'))

    if data is None:
        print('Failed to download from: {url}.'.format(url=url))
        exit(1)

    print(data['info']['Version'])
