#!/usr/bin/env python
import os, sys
import sr_commands
TOOLS = os.path.join( sys.path[0], "../" )

for cmd, path in sr_commands.get_dict(TOOLS).items():
    if cmd[0] != "_" and cmd[-1] != "~":
        print(cmd)
