#!/usr/bin/env python
from __future__ import print_function

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

import sr.tools.cli


print('Warning: You are running an old version of the tools.', file=sys.stderr)

sr.tools.cli.main()
