#!/usr/bin/env python
import sys, os, subprocess
TOOLS_DIR = os.path.join( sys.path[0], "../" )

# Perform the svn up
print "Updating subversion...",
sys.stdout.flush()

p = subprocess.Popen( "svn up -q",
                      cwd = TOOLS_DIR,
                      shell = True )
p.communicate()
p.wait()
print "done."
