#!/usr/bin/env python
from __future__ import print_function

import os
import sys

import sr.tools.inventory as srinv
from sr.tools.inventory import assetcode, oldinv, normalise_partcode, get_inventory
from sr.tools.environment import open_editor


if len(sys.argv) < 2:
    print("Usage: inv-edit PART_CODES", file=sys.stderr)
    exit(1)



inv = get_inventory()

parts = []
for c in sys.argv[1:]:
    code = normalise_partcode(c)

    try:
        assetcode.code_to_num(code)
    except:
        print("Error: %s is an invalid code." % code, file=sys.stderr)
        exit(1)

    try:
        part = inv.root.parts[code]
    except KeyError:
        print("Error: There is no part with code %s." % code, file=sys.stderr)
        exit(1)

    parts.append(part)

editor = os.environ.get("EDITOR", "vi")

for part in parts:
    open_editor(part.path)
