#!/usr/bin/env python

import json

try:
    import urllib.request as urllib
except ImportError:
    import urllib

import sys, re


if len(sys.argv) > 2 or (len(sys.argv) == 2 and sys.argv[1] == '--help'):
    print('Usage: repolist [REGEX]')
    exit()

matcher = None
if len(sys.argv) == 2:
    matcher = re.compile(sys.argv[1])

u = urllib.urlopen('https://www.studentrobotics.org/gerrit/projects/?d')

raw_json = u.read().decode('utf-8')

NO_EXEC_PREFIX = ')]}\''
if raw_json.startswith(NO_EXEC_PREFIX):
    raw_json = raw_json[len(NO_EXEC_PREFIX):].strip()

projects_map = json.loads(raw_json)

paths = sorted(projects_map.keys())
for path in paths:
    path += '.git'
    if matcher is None or matcher.search(path):
        print(path)
