#!/usr/bin/env python
from __future__ import print_function

import sr.tools.bom.digikey as digikey
import sys

if len(sys.argv) > 1:
	id = sys.argv[1]
else:
	print 'Note: you can also specify a part number as a command line argument.'
	id = ''
	while id == '':
		id = raw_input('Enter part number: ')

item = digikey.Item(id)
item.print_info()
