#!/usr/bin/env python
from __future__ import print_function

import argparse
import sys

import sr.tools.bom.eagle as eagle


parser = argparse.ArgumentParser(description='Show version of an EAGLE file.')
parser.add_argument('file', help='The file to test.')
args = parser.parse_args()

v = eagle.file_version(args.file)
print("%i.%i" % v)
