#!/usr/bin/env python
from __future__ import print_function

import argparse
import io
import sys

import sr.tools.bom.farnell as farnell


parser = argparse.ArgumentParser(description='Get information about a part from Farnell.')
parser.add_argument('id', nargs='*', help='IDs to get information about.')
args = parser.parse_args()

if args.id:
    ids_stream = io.StringIO('\n'.join(args.id))
else:
    print('Reading from stdin.', file=sys.stderr)
    ids_stream = sys.stdin

line = ids_stream.readline()
while line:
    item = farnell.Item(line.strip())
    item.print_info()
    line = ids_stream.readline()
