#!/usr/bin/env python
import os, sys, parts_db, parts_parser, bom, tempfile

if len(sys.argv) < 2:
    print "Usage: %s SCHEMATIC" % os.path.basename(sys.argv[0])
    print "Checks that all the parts in a PCB's schematic are in the SR database"
    sys.exit(1)

PARTS_DB = os.path.expanduser("~/.sr/tools/bom/sr_component_lib")
if not os.path.exists( PARTS_DB ):
    print "Parts DB not found at \"%s\"" % PARTS_DB
    sys.exit(1)

SCHEMATIC = sys.argv[1]

# Generate the BOM from the given schematic
bom_tup = tempfile.mkstemp()
os.close(bom_tup[0])
BOM_FNAME = bom_tup[1]

# TODO: move more into bom.py
bom.export_bom( SCHEMATIC, BOM_FNAME )

lib = parts_db.Db(PARTS_DB)
parts = parts_parser.EagleParts(BOM_FNAME)

bom = {}

error = 0
found = 0

for id in parts.keys():
    if not lib.has_key( parts[id] ):
        print "Error (%s): '%s' not in SR component database, please re-align your mind" % (id, parts[id])
        error = error + 1
    else:
        found = found + 1

print found,"parts checked in",PARTS_DB
if error > 0:
    print "Fail:", error, "parts not identified"
    sys.exit(2)


