#!/usr/bin/env python
import sys, os
import bom, parts_db
from pylab import *

if len(sys.argv) < 2:
   print "Usage: %s DIR -N SCHEMATIC1 -M SCHEMATIC2 ..." % os.path.basename( sys.argv[0] )
   print """
	Where N and M are multipliers for the number of boards."""
   sys.exit(1)

db = parts_db.Db( bom.PARTS_DB )
m = bom.MultiBoardBom(db)
m.load_boards_args( sys.argv[1:] )

prices = []

for srcode, pg in m.iteritems():
   if srcode == "sr-nothing":
      continue

   prices.append( (srcode, pg.get_price()) )

def cmp_prices(a,b):
   return cmp( a[1], b[1] )

prices.sort( cmp = cmp_prices )

bar( range(0, len(prices)),
     [x[1] for x in prices] )

xticks( arange(0, len(prices)) + 0.5,
        [x[0] for x in prices],
        rotation = 90 )

show()

