#!/usr/bin/env python
import sys, os, threading, Queue
import bom, parts_db, schem
NUM_THREADS = 3

if len(sys.argv) < 2:
    print "Usage: %s SCHEMATIC" % os.path.basename(sys.argv[0])
    sys.exit(1)

db = parts_db.Db( bom.PARTS_DB )
board = bom.BoardBom( db, sys.argv[1], os.path.basename( sys.argv[1] ) )
stock = {}
n = 0

for x in board.stockcheck():
    if not stock.has_key(x[0]):
        stock[x[0]] = []

    stock[ x[0] ].append(x[1])

    # Show stock checking progress:
    n = n + 1
    sys.stdout.write( "\rChecking: %i/%i" % (n, len(board)) )
    sys.stdout.flush()
print

if stock.has_key( bom.STOCK_UNKNOWN ):
    print "Warning: Cannot check suppliers for these parts:"
    for part in stock[bom.STOCK_UNKNOWN]:
        print "\t- %s %s(%s)" % ( part["sr-code"], part["supplier"], part["order-number"] )

if stock.has_key( bom.STOCK_OUT ):
    print "Out of stock:"
    for part in stock[bom.STOCK_OUT]:
        print "\t- %s %s(%s)" % ( part["sr-code"], part["supplier"], part["order-number"] )
    sys.exit(1)

print "All checkable parts are in stock."
sys.exit(0)
