#!/usr/bin/env python
from __future__ import print_function

import sr.tools.bom.eagle as eagle
import sys

if len(sys.argv) != 2:
    print("Usage: eagle_ver.py SCH_FILE")
    sys.exit(1)

v = eagle.file_version( sys.argv[1] )
print("%i.%i" % v)
