#!/usr/bin/env python
from __future__ import print_function

import sys, os
import sr.tools.bom.bom as bom
import sr.tools.bom.parts_db as parts_db
from pylab import *

if len(sys.argv) < 2:
   print("Usage: %s DIR -N SCHEMATIC1 -M SCHEMATIC2 ..." % os.path.basename( sys.argv[0] ))
   print("""
    Where N and M are multipliers for the number of boards.""")
   sys.exit(1)

db = parts_db.get_db()
m = bom.MultiBoardBom(db)
m.load_boards_args( sys.argv[1:] )
m.prime_cache()

prices = []

for srcode, pg in m.items():
   if srcode == "sr-nothing":
      continue

   prices.append( (srcode, pg.get_price()) )

def cmp_prices(a,b):
   return cmp( a[1], b[1] )

prices.sort( cmp = cmp_prices )

bar( 0, 0.8, bottom=range(0, len(prices)),
     width=[x[1] for x in prices], orientation='horizontal' )

yticks( arange(0, len(prices)) + 0.4 ,
        [x[0] for x in prices])

subplots_adjust( left = 0.35 )

show()
