#!/usr/bin/env python
from __future__ import print_function

import pysric

def cmp_dev_address(x,y):
    return cmp(x.address, y.address)

p = pysric.PySric()

all_devs = []
for devtype, devs in p.devices.items():
    for dev in devs:
        all_devs += [dev]

all_devs.sort(cmp = cmp_dev_address)

padding = " "
fields = ["Address", "Type"]
title_line = padding + (padding * 2).join(fields)
print(title_line)
print("-" * len(title_line))

for dev in all_devs:
    vals = [ dev.address, pysric.sric_class_strings[dev.type] ]
    vals = [str(x) for x in vals]

    assert len(vals) == len(fields)

    for i in range(0,len(fields)):
        width = len(fields[i]) + len(padding)
        val = padding + vals[i]

        print("%s%s" % (val, " " * (width-len(val))), end='')
    print()
